task_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_user, name='logout'),
    path('', views.task_list, name='task_list'),
    path('create/task/', views.create_task, name='create_task'),
    path('tasks/<int:task_id>/delete/', views.delete_task, name='delete_task'),
    path('tasks/<int:task_id>/update/', views.update_task, name='update_task'),
    path('search/', views.search_view, name='search'),
]

task_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('task_app.urls')),
]

task_app/models.py
from django.db import models
from django.contrib.auth.models import User


class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=256)
    description = models.TextField()
    category = models.CharField(max_length=20)
    created = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.title

task_app/forms.py
from django import forms
from .models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'category']


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

task_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .models import Task
from django.db.models import Q
from .forms import TaskForm, LoginForm


# LOGIN
def login_user(request):
    if request.user.is_authenticated:
        return redirect('task_list')
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('task_list')
    else:
        form = LoginForm()
    return render(request, 'login.html', {'form': form})


# REGISTER
def register(request):
    if request.user.is_authenticated:
        return redirect('task_list')
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('task_list')
        else:
            messages.error(
                request, 'Invalid registration details. Please try again.')
    else:
        form = UserCreationForm()
    return render(request, 'register.html', {'form': form})


# BASE
@login_required(login_url='login')
def base(request):
    return render(request, 'base.html')


# VIEW
@login_required(login_url='login')
def task_list(request):
    tasks = Task.objects.filter(user=request.user)
    return render(request, 'task_list.html', {'tasks': tasks})


# CREATE
@login_required(login_url='login')
def create_task(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.user = request.user
            task.save()
            return redirect('task_list')
    else:
        form = TaskForm()
    return render(request, 'task_create.html', {'form': form})


# UPDATE
@login_required(login_url='login')
def update_task(request, task_id):
    task = get_object_or_404(Task, pk=task_id, user=request.user)
    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect('task_list')
    else:
        form = TaskForm(instance=task, initial={'category': task.category})
    return render(request, 'task_update.html', {'form': form})


# DELETE
@login_required(login_url='login')
def delete_task(request, task_id):
    task = get_object_or_404(Task, pk=task_id, user=request.user)
    if request.method == 'POST':
        task.delete()
        return redirect('task_list')
    return render(request, 'task_confirm_delete.html', {'task': task})


# SEARCH
def search_view(request):
    search_input = request.GET.get('search-area', '')
    tasks = Task.objects.filter(Q(title__icontains=search_input))
    return render(request, 'search_results.html', {'tasks': tasks, 'search_input': search_input})


# LOGOUT
@login_required(login_url='login')
def logout_user(request):
    logout(request)
    return redirect('login')

task_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ToDo</title>
    <link rel="stylesheet" href="/static/style.css">
    <script src="https://kit.fontawesome.com/6634b5a360.js" crossorigin="anonymous"></script>
    
</head>
<body>

    <div class="container">
    {% block content %}
    {% endblock content %}
</div>
    
</body>
</html>

task_app/templates/login.html
{% extends "base.html" %}
{% block content %}


<div class="header-bar">
    <h1>Login</h1>
</div>


<div class="card-body">
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input class="button" type="submit" value="Login">
        <p>Don't have an account? <a href="{% url 'register' %}">Register</a></p>
    </form>
</div>

{% endblock content %}

task_app/templates/register.html
{% extends "base.html" %}
{% block content %}

<div class="header-bar">
    <h1>Register</h1>
    <a href="{% url 'task_list' %}">&#8592; Back</a>
</div>


<div class="card-body">
    <form method="POST">
        {% csrf_token %}
        <label>{{ form.username.label }}</label>
        {{ form.username }}
        {{ form.username.errors }}

        <label>{{ form.password1.label }}</label>
        {{ form.password1 }}
        {{ form.password1.errors }}

        <label>{{ form.password2.label }}</label>
        {{ form.password2 }}
        {{ form.password2.errors }}

        <input style="margin-top: 20px;" class="button" type="submit" value="Register">
        <p>Already have an account? <a href="{% url 'login' %}">Login</a></p>
    </form>
    
</div>

{% endblock content %}

task_app/templates/search_results.html
{% extends 'base.html' %}
{% block content %}

<div class="header-bar">
  <h2>Search Results</h2>
  <a href="{% url 'task_list' %}">&#8592; Back</a>
</div>

<div class="task-list">
  {% if tasks %}
      <div class="header">
          <p>Title</p>
          <p>Description</p>
          <p>Category</p>
          <p>Created Date</p>
      </div>

      {% for task in tasks %}
          <div class="row">
              <p>{{task.title | title}}</p>
              <p>{{ task.description }}</p>
              <p>{{ task.category | title }}</p>
              <p>{{ task.created }}</p>
          </div>

         
      {% endfor %}
  {% else %}
      <div class="row">
          <h2>No matching task found</h2>
      </div>
  {% endif %}
</div>

{% endblock content %}

task_app/templates/task_confirm_delete.html
{% extends "base.html" %}
{% block content %}

<div class="header-bar">
    <a href="{% url 'task_list' %}">&#8592; Back</a>
</div>


<div class="card-body">
    <form method="POST" action="{% url 'delete_task' task.id %}">
        {% csrf_token %}
        <p>Are you sure you want to delete this task? <strong>{{ task.title | title }}</strong></p>
        <input class="button" type="submit" value="Delete">
    </form>
</div>


{% endblock content %}

task_app/templates/task_create.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<div class="header-bar">
    <h1>Create Task</h1>
    <a href="{% url 'task_list' %}">&#8592; Back</a>
</div>

<div class="card-body">
    <form method="post" id="task-form" onsubmit="return validateForm()">
        {% csrf_token %}
        <label for="id_title">Title:</label>
        <input type="text" name="title" id="id_title">

        <label for="id_description">Description:</label>
        <textarea name="description" id="id_description" rows="5"></textarea>

        <label for="id_category">Category:</label>
        <input type="text" name="category" id="id_category"></input>

        
        <button type="submit" class="button">Create</button>
    </form>
</div>


<script src="{% static 'js/create_validation.js' %}"></script>

{% endblock content %}

task_app/templates/task_list.html
{% extends "base.html" %}
{% block content %}
{% load static %}


<div class="header-bar">
    <h1>Welcome {{ user.username | title }}</h1>
    <a href="{% url 'logout' %}">Logout</a>
</div>


<div id="search-add-wrapper">
    <form id="search-form" method="GET" action="{% url 'search' %}" style="margin-top: 20px; display: flex;" onsubmit="return validateSearchForm()">
        <div style="position: relative;">
            <input type="text" name='search-area' id="search-area" value="{{ search_input }}" style="background-color: ''; position: relative;">
        </div>
        <input class="search-button" type="submit" value="Search">
    </form>
    <a id="add-link" href="{% url 'create_task' %}">&#x2b;</a>
</div>



<div class="task-list">
    {% if tasks %}
        <div class="header">
            <p>Title</p>
            <p>Description</p>
            <p>Category</p>
            <p>Created Date</p>
            <p></p>
        </div>

        {% for task in tasks %}
            <div class="row">
                <p>{{task.title | title}}</p>
                <p>{{ task.description }}</p>
                <p>{{ task.category | title }}</p>
                <p>{{ task.created }}</p>
                <p style="display: flex; gap: 30px;">
                    <a href="{% url 'update_task' task.id %}">
                        <i class="fa-solid fa-pen-to-square"></i>
                    </a>
                    <a href="{% url 'delete_task' task.id %}">
                        <i class="fa-solid fa-trash"></i>
                    </a>
                </p>
            </div>

           
        {% endfor %}
    {% else %}
        <div class="row">
            <h2>No tasks available</h2>
        </div>
    {% endif %}
</div>

<script src="{% static 'js/search_validation.js' %}"></script>


{% endblock %}

task_app/templates/task_update.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<div class="header-bar">
    <h2>Update Task</h2>
    <a href="{% url 'task_list' %}">&#8592; Back</a>
</div>

<div class="card-body">
    <form method="post">
        {% csrf_token %}
        <label for="id_title">Title:</label>
        {{ form.title }}

        <label for="id_description">Description:</label>
        {{ form.description }}

        <label for="id_category">Category:</label>
        {{ form.category }}

        <button type="submit" class="button">Update</button>
    </form>
</div>


{% endblock content %}